# Generated by Django 4.1.1 on 2022-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3)),
                ('exc_date', models.DateTimeField(verbose_name='Exchange rate date')),
                ('value', models.IntegerField(default=1)),
            ],
        ),
    ]
