# Generated by Django 4.1.1 on 2022-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_euro_iso_code_real_iso_code_yen_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euro',
            name='iso_code',
            field=models.CharField(default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='real',
            name='iso_code',
            field=models.CharField(default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='yen',
            name='iso_code',
            field=models.CharField(default='JPY', editable=False, max_length=3),
        ),
    ]
